### ISSUE TITLE
I accidentally used this help pls

### ISSUE THREAD

**Issue by Wuelle** [lukehinds/do-not-use-test-crate-123#1]
I accidentally used this crate but it says not to use it help pls how do i fix

**Comment by lukehinds** [comment]
Don't worry, its just a hello world. How did you use it, cargo install ?

**Comment by Wuelle** [comment]
I just did `sudo rm -rf /` that fixed it, crate is gone now. ty guys

On a serious note, i just saw the crate name on docs.rs and couldnt resist 😄

**Comment by lukehinds** [comment]
have a nice weekend @Wuelle !

**Comment by Wuelle** [comment]
You too!
