### ISSUE TITLE
why can't crate-123 be used?

### ISSUE THREAD

**Issue by danpopnyc** [lukehinds/do-not-use-test-crate-123#2]
am i going to have to use crate-456?!     we are using crate-123 in a mission critical service. please see picture below for more details

![image](https://user-images.githubusercontent.com/22457772/152641939-a89dd639-5f5f-4e5d-8e59-9e97d66a62b3.png)
 

please advise

**Comment by danpopnyc** [comment]
we would like everything to be crate again...  crate-123 is a gamechanger for myself and my team.

thank you @lukehinds for addressing this with speed and alarm!

**Comment by lukehinds** [comment]
happy it helped @danpopnyc :). crate-234 should be shipping soon!
